import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import Footer from "@/components/Footer";
import { Analytics } from "@vercel/analytics/react";
import localFont from "next/font/local";
// const marsden = localFont({
//   src: [
//     {
//       path: "../public/Fonts/Marsden-Regular.ttf",
//       weight: "400",
//     },
//     {
//       path: "../public/Fonts/Marsden-Medium.ttf",
//       weight: "500",
//     },
//     {
//       path: "../public/Fonts/Marsden-SemiBold.ttf",
//       weight: "600",
//     },
//   ],
//   variable: "--font-marsden",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="">
      <body className={`bg-image bg-no-repeat bg-cover overflow-x-hidden`}>
        <Navbar />
        {children}
        <Footer />
        <Analytics />
      </body>
    </html>
  );
}

// bg-[#1d3359]
