import Navbar from '@/components/Navbar';
import './globals.css';
import type { Metadata } from 'next';
import Footer from '@/components/Footer';
import { Analytics } from '@vercel/analytics/react';
import NextTopLoader from 'nextjs-toploader';

// const marsden = localFont({
//   src: [
//     {
//       path: "../public/Fonts/Marsden-Regular.ttf",
//       weight: "400",
//     },
//     {
//       path: "../public/Fonts/Marsden-Medium.ttf",
//       weight: "500",
//     },
//     {
//       path: "../public/Fonts/Marsden-SemiBold.ttf",
//       weight: "600",
//     },
//   ],
//   variable: "--font-marsden",
// });

export const metadata: Metadata = {
  title: 'KI.m',
  description: 'Generated by create next app',
  viewport:
    'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className=''>
      <body className={`overflow-x-hidden bg-image bg-cover bg-no-repeat`}>
        <NextTopLoader />
        <Navbar />
        <div className=''>{children}</div>
        <Footer />
        <Analytics />
      </body>
    </html>
  );
}

// bg-[#1d3359]
